### ISSUE TITLE
How to remove the attachment of ttyAMA0 exactly?

### ISSUE THREAD

**Issue by rdinse** [RoEdAl/alarm-bluetooth-raspberrypi#2]
I'm trying to install this package on an RPi Zero W (v. 1.2).

> Remove the attachment of /dev/ttyAMA0 (/dev/ttyS0 in mini-UART version) to the console from /boot/cmdline.txt.

Does this mean to simply change the arguments `console=ttyAMA0,115200` to `console=115200` and `kgdboc=ttyAMA0,115200` to `kgdboc=115200`?

**Comment by RoEdAl** [comment]
No - just remove whole `console` (and/or `kgdboc`) kernel parameter.
